server:
  port: ${PORT:9999}

messages:
  home: Hello, Memorynotfound!

spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    prefix: /WEB-INF/views/
    suffix: .jsp
    # template-resolver-order:
    # view-names:

logging:
  level:
  - ".=info"
  - "com.memorynotfound=debug"
  - "org.springframework=info"